#include "generator.bi"

function generate_makefile(yoarfile_path as string, base_dir as string, target as string) as integer
  dim yc as YoarConfig
  dim res as integer

  res = parse_yoar_file(yoarfile_path, yc)

  if res = 0 then
    print "parse failed"
    end 1
  end if

  print "parsed successfully"

  dim as ubyte of = freefile

  if open("makefile" for output as #of) <> 0 then
    print "makefile could not be opened for writing..."
    end
  end if

  print #of, "# generated by yoar"
  print #of, ""

  print #of, "CC = " & yc.fbc

  '' write sources ''
  if yc.source_count = 0 then
    print "[error] no sources defined in Yoarfile"
    end
  end if
  print #of, "SOURCES = ";
  for i as integer = 0 to yc.source_count - 1
    print #of, base_dir & "/" & yc.sources(i);
    if i <> yc.source_count - 1 then
      print #of, " ";
    end if
  next
  print #of, ""

  '' write includes ''
  if yc.include_count <> 0 then
    print #of, "INCLUDES = ";
    for i as integer = 0 to yc.include_count - 1
      print #of, "-i " & base_dir & "/" & yc.includes(i);
      if i <> yc.include_count - 1 then
        print #of, " ";
      end if
    next
    print #of, ""
  end if

  '' write libs ''
  if yc.lib_count <> 0 then
    print #of, "LIBS = ";
    for i as integer = 0 to yc.lib_count - 1
      print #of, yc.libs(i);
      if i <> yc.lib_count - 1 then
        print #of, " ";
      end if
    next
    print #of, ""
  end if

  '' write links ''
  if yc.link_count <> 0 then
    print #of, "LFLAGS = ";
    for i as integer = 0 to yc.link_count - 1
      print #of, "-l" & yc.links(i);
      if i <> yc.link_count - 1 then
        print #of, " ";
      end if
    next
    print #of, ""
  end if

  '' build targets ''
  select case target
    case "release"
      print #of, "FLAGS = " & yc.release
    case "debug"
      print #of, "FLAGS = " & yc.debug
    case "test"
      print #of, "FLAGS = " & yc.test
    case else
      print "unkown target: " & target
      return 0
  end select

  '' write output ''
  print #of, "OUTPUT = " & yc.proj_output & "/" & yc.proj_name & !"\n"

  print #of, "${OUTPUT}: ${SOURCES}"
  print #of, !"\tmkdir -p " & yc.proj_output
  if yc.pre_build <> "" then print #of, !"\t@$(MAKE) pre_build"
  print #of, !"\t${CC} ${FLAGS} ${SOURCES} ${INCLUDES} ${LIBS} ${LFLAGS} -x ${OUTPUT}"
  if yc.post_build <> "" then print #of, !"\t@$(MAKE) post_build"

  print #of, ""

  if yc.pre_build <> "" then
    print #of, "pre_build:"
    print #of, !"\t" & yc.pre_build
    print #of, ""
  end if

  if yc.post_build <> "" then
    print #of, "post_build:"
    print #of, !"\t" & yc.post_build
    print #of, ""
  end if

  '' clean ''
  print #of, "clean:"
  print #of, !"\trm " & yc.proj_output & "/" & yc.proj_name

  print #of, ""

  '' run ''
  print #of, "run:"
  print #of, !"\t./" & yc.proj_output & "/" & yc.proj_name

  print #of, ""

  '' run yoar when yoarfile changes ''
  print #of, "makefile: " & yoarfile_path
  print #of, !"\tyoar " & base_dir

  return 1
end function
