#include "generator.bi"

function generate_makefile(yoarfile_path as string) as integer
  dim yc as YoarConfig
  dim res as integer

  res = parse_yoar_file(yoarfile_path, yc)

  if res = 0 then
    print "parse failed"
    end 1
  end if

  print "parsed successfully"

  dim as ubyte of = freefile

  if open("makefile" for output as #of) <> 0 then
    print "makefile could not be opened for writing..."
    end
  end if

  print #of, "# generated by yoar"

  return 1
end function
