#include "generator.bi"

function generate_makefile(yoarfile_path as string) as integer
  dim yc as YoarConfig
  dim res as integer

  res = parse_yoar_file(yoarfile_path, yc)

  if res = 0 then
    print "parse failed"
    end 1
  end if

  print "parsed successfully"

  dim as ubyte of = freefile

  if open("makefile" for output as #of) <> 0 then
    print "makefile could not be opened for writing..."
    end
  end if

  print #of, "# generated by yoar"
  print #of, ""

  print #of, "CC = " & yc.fbc

  '' write sources ''
  print #of, "SOURCES = ";
  for i as integer = 0 to yc.source_count - 1
    print #of, yc.sources(i);
    if i <> yc.source_count - 1 then
      print #of, " ";
    end if
  next
  print #of, ""

  '' write includes ''
  print #of, "INCLUDES = ";
  for i as integer = 0 to yc.include_count - 1
    print #of, "-i " & yc.includes(i);
    if i <> yc.include_count - 1 then
      print #of, " ";
    end if
  next
  print #of, ""

  print #of, "OUTPUT = " & yc.proj_output & "/" & yc.proj_name

  dim as boolean debug = yc.debug <> "", release = yc.release <> "", test = yc.test <> ""

  if debug then
    print #of, "DEBUG_FLAGS = " & yc.debug
  end if
  if  release then
    print #of, "RELEASE_FLAGS = " & yc.release
  end if
  if  test then
    print #of, "TEST_FLAGS = " & yc.test
  end if

  print #of, ""

  if debug then
    print #of, "debug: ${SOURCES}"
    print #of, !"\t${CC} ${DEBUG_FLAGS} ${SOURCES} ${INCLUDES} -x ${OUTPUT}"
  end if

  if release then
    print #of, "release: ${SOURCES}"
    print #of, !"\t${CC} ${RELEASE_FLAGS} ${SOURCES} ${INCLUDES} -x ${OUTPUT}"
  end if

  if test then
    print #of, "test: ${SOURCES}"
    print #of, !"\t${CC} ${TEST_FLAGS} ${SOURCES} ${INCLUDES} -x ${OUTPUT}"
  end if

  print #of, ""

  print #of, "clean: "
  print #of, !"\trm " & yc.proj_output & "/" & yc.proj_name

  return 1
end function
